apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-{{ include "fastapimeals-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mealsapp
    version: {{.Chart.AppVersion}}
data:
  POSTGRES_DB: ZmFzdGFwaW1lYWxzZGI=         # fastapimealsdb
  POSTGRES_USER: ZmFzdGFwaW1lYWxz           # fastapimeals
  POSTGRES_PASSWORD: ZmFzdGFwaW1lYWxzMTIz   # fastapimeals123