apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fastapimeals-namespace
  labels:
    app: mealsapp
data:
  default.conf: |
    upstream mealsapp_proxy {
        server mealsapp-service:5000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://mealsapp_proxy;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }