apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: fastapimeals-namespace
  labels:
    app: mealsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mealsapp-nginx
  template:
    metadata:
      labels:
        app: mealsapp-nginx
    spec:
      containers:
        - image: nginx:1.23
          name: nginx-container
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 80
              path: /docs
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
