"""empty message

Revision ID: 0efa712363fc
Revises: 95049117e202
Create Date: 2022-08-28 10:47:35.761799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efa712363fc'
down_revision = '95049117e202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
