apiVersion: v1
kind: Secret
metadata:
  name: mealsapp-secret-{{ include "fastapimeals-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mealsapp
    version: {{ .Chart.AppVersion }}
data:
  DATABASE_USERNAME: ZmFzdGFwaW1lYWxz       # fastapimeals
  DATABASE_PASSWORD: ZmFzdGFwaW1lYWxzMTIz   # fastapimeals123
  DATABASE_HOST: cG9zdGdyZXMtc2VydmljZQ==   # postgres-service
  DATABASE_NAME: ZmFzdGFwaW1lYWxzZGI=       # fastapimealsdb