apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fastapimeals-namespace
  labels:
    app: mealsapp
data:
  POSTGRES_DB: ZmFzdGFwaW1lYWxzZGI=         # fastapimealsdb
  POSTGRES_USER: ZmFzdGFwaW1lYWxz           # fastapimeals
  POSTGRES_PASSWORD: ZmFzdGFwaW1lYWxzMTIz   # fastapimeals123