apiVersion: v1
kind: Secret
metadata:
  name: mealsapp-secret
  namespace: fastapimeals-namespace
  labels:
    app: mealsapp
data:
  DATABASE_USERNAME: ZmFzdGFwaW1lYWxz       # fastapimeals
  DATABASE_PASSWORD: ZmFzdGFwaW1lYWxzMTIz   # fastapimeals123
  DATABASE_HOST: cG9zdGdyZXMtc2VydmljZQ==   # postgres-service
  DATABASE_NAME: ZmFzdGFwaW1lYWxzZGI=       # fastapimealsdb