apiVersion: v1
kind: Service
metadata:
  name: mealsapp-service
  namespace: fastapimeals-namespace
  labels:
    app: mealsapp
spec:
  selector:
    app: mealsapp-app
  ports:
    - port: 5000
      targetPort: 5000